# Site settings
title: Denny's Website
email: jaryguo1990@163.com
description: > # this means to ignore newlines until "baseurl:"
  Personal blog，used Jekyll & running on Github
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jaryguo.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  jaryguo

timezone: Asia/Shanghai

# Build settings
markdown: kramdown



kramdown:
  input: GFM
